export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';


//All user todos
export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const GET_ALL_TODOS_ERROR = 'GET_ALL_TODOS_ERROR';


// Authenticated user todos
export const GET_USER_TODOS = 'GET_USER_TODOS';
export const GET_USER_TODOS_ERROR = 'GET_USER_TODOS_ERROR';


export const ADD_USER_TODO = 'ADD_USER_TODO';
export const ADD_USER_TODO_ERROR = 'ADD_USER_TODO_ERROR';

export const UPDATE_TODO_BY_ID = 'UPDATE_TODO_BY_ID';
export const UPDATE_TODO_BY_ID_ERROR = 'UPDATE_TODO_BY_ID_ERROR';

export const DELETE_TODO_BY_ID = 'DELETE_TODO_BY_ID';
export const DELETE_TODO_BY_ID_ERROR = 'DELETE_TODO_BY_ID_ERROR';

export const GET_USER_EVENTS = 'GET_USER_EVENTS';
export const GET_USER_EVENTS_ERROR = 'GET_USER_EVENTS_ERROR';
export const ADD_USER_EVENT = 'ADD_USER_EVENT';
export const ADD_USER_EVENT_ERROR = 'ADD_USER_EVENT_ERROR';
export const DELETE_EVENT_BY_ID_ERROR = 'DELETE_EVENT_BY_ID_ERROR';

export const GET_SPECIFIC_EVENT = 'GET_SPECIFIC_EVENT';
export const GET_SPECIFIC_EVENT_ERROR = 'GET_SPECIFIC_EVENT_ERROR';

export const LOAD_SPECIFIC_EVENT_ID = 'LOAD_SPECIFIC_EVENT_ID';
export const LOAD_SPECIFIC_EVENT_ID_ERROR = 'LOAD_SPECIFIC_EVENT_ID_ERROR';
export const DELETE_SPECIFIC_EVENT_BY_ID_ERROR = 'DELETE_SPECIFIC_EVENT_BY_ID_ERROR';

export const UPDATE_EVENT_BY_ID = 'UPDATE_EVENT_BY_ID';
export const UPDATE_EVENT_BY_ID_ERROR = 'UPDATE_EVENT_BY_ID_ERROR';

// Authenticate user action types
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

export const POST_MESSAGE = 'POST_MESSAGE';
export const POST_MESSAGE_ERROR = 'POST_MESSAGE_ERROR';

// Get messages action types
export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_MESSAGE_ERROR = 'GET_MESSAGE_ERROR';